const controller = require("../controllers/users.controllers")
module.exports = function (app) {
    app.post(
        '/api/users/login',
        controller.login
    ) 
    app.post(
        '/api/users/signUp',
        controller.signUp
    )
    app.get(
        '/api/users/resetPassword',
        controller.resetPassword
    )
    app.post(
        '/api/users/change-password',
        controller.changePassword
    )
    app.get(
        '/api/users/findOne',
        controller.findOne
    )
    app.get(
        '/api/users/findOneEmail',
        controller.findOneEmail
    )
    app.post(
        '/api/users/signUpDoorman',
        controller.signUpDoorman
    )
    app.get(
        '/api/users/active-user',
        controller.activeUser
    )
    app.post(
        '/api/users/contact',
        controller.contact
    )
    app.post(
        '/api/users/sendNotice',
        controller.sendNotice
    )
    app.post(
        '/api/users/sendTicket',
        controller.sendTicket
    )
}